---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_overview.html 
sidebar: sidebar 
keywords: SnapCenter Custom Plug-ins 
summary: 使用するアプリケーション用のカスタムプラグインを開発し、 SnapCenter を使用してそれらのアプリケーションのバックアップ、リストア、クローニングを行うことができます。カスタムプラグインは、他の SnapCenter プラグインと同様に NetAppSnap Center ソフトウェアのホスト側コンポーネントとして機能し、アプリケーションに対応したリソースのデータ保護と管理を実現します。 
---
= SnapCenter Custom Plug-ins の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用するアプリケーション用のカスタムプラグインを開発し、 SnapCenter を使用してそれらのアプリケーションのバックアップ、リストア、クローニングを行うことができます。カスタムプラグインは、他の SnapCenter プラグインと同様に NetApp SnapCenter ソフトウェアのホスト側コンポーネントとして機能し、アプリケーションに対応したリソースのデータ保護と管理を実現します。

Custom Plug-ins をインストールすると、 SnapCenter と NetApp SnapMirror テクノロジを使用して別のボリュームのバックアップセットのミラーコピーを作成し、 NetApp SnapVault テクノロジを使用してディスクツーディスクのバックアップレプリケーションを実行できます。Custom Plug-ins は、 Windows と Linux のどちらの環境でも使用できます。


NOTE: SnapCenter CLI では、 SnapCenter Custom Plug-ins コマンドはサポートされていません。

NetApp は、SnapCenter Software 2.0 以降で MySQL および DB2 カスタムプラグインを、3.0 以降で MongoDB カスタムプラグインを提供しています。


NOTE: MySQL 、 DB2 、 MongoDB のカスタムプラグインは、ネットアップのコミュニティでのみサポートされます。

独自のカスタムプラグインは、を参照して作成できます link:concept_develop_a_plug_in_for_your_application.html["アプリケーション用のプラグインを開発します"^]。
